import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@telegram-apps/telegram-ui/dist/styles.css';
import './globals.css';
import { Root } from '@/components/Root/Root';
import { AuthProvider } from '@/components/Auth/AuthProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Root>
          <AuthProvider>{children}</AuthProvider>
        </Root>
      </body>
    </html>
  );
}
